### ISSUE TITLE
Game is not responding for 5 minutes every time i open it

### ISSUE THREAD

**Issue by Cooxie1** [OpenSauce04/Epiphany#16] opened 2022-10-26 14:47 UTC
**Describe the bug**
i need to wait 5 minutes for the game to load because it isnt responding it 

**To Reproduce**
---

**Log**
---

**Screenshots**
---

**Version information:**
1.0
 - Installed wave number: 
 - Version number: 
wave 4
**Additional context**
---

**Comment by Cooxie1** [comment] 2022-10-26 14:53
also when i go into the menu

**Comment by OpenSauce04** [comment] 2022-10-30 09:39
I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

**Comment by OpenSauce04** [comment] 2022-11-01 18:18
Duplicate of

**Closed by OpenSauce04** 2022-11-01 18:18 UTC
Labels: Duplicate

**Comment by Kyedae69** [comment] 2023-01-08 12:07
i have the exact same issue everytime i start the game with the mod installed my game doesnt respond but if i delete the mod it starts normaly

> I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

**Comment by AstralTM** [comment] 2023-05-18 21:47
> I think I know what's happening here, can you run EpiphanyDiag and send me the produced file? I might be able to fix it for you

i have the same issue, here is my EpiphanyDiag

the game is normally functioning, but if i will put the epiphany file into the mods then the game won't open.

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11511793/EpiphanyDiagnostics.tar.gz)
